# highly inspired by https://github.com/grafana/loki/blob/4cae003e/operator/hack/addons_traefik.yaml#L133
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: ${TRAEFIK_NAMESPACE}
data:
  config.yaml: |
    http:
      middlewares:
        waf:
          plugin:
            coraza:
              directives:
                - SecRuleEngine DetectionOnly
                - SecDebugLog /dev/stdout
                - SecDebugLogLevel 9
                - SecRule REQUEST_URI "@streq /headers" "id:101,phase:1,log,deny,status:403"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wasm-plugin-manifest
  namespace: ${TRAEFIK_NAMESPACE}
data:
  .traefik.yml: |
    displayName: Coraza WAF
    runtime: wasm
    type: middleware
    summary: Coraza WAF http-wasm middleware
    wasmPath: coraza-http-wasm.wasm
    testData:
      directives:
        - SecRuleEngine DetectionOnly
